version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - development
    ports:
      - "3000:3000"  # Next.js
      - "3001:3001"  # Rails API
      
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_development
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    networks:
      - development

networks:
  development:

volumes:
  mysql-data:
