openapi: 3.0.0
info:
  title: Backend External API
  version: 1.0.0
  description: 外部向けのAPI定義
servers:
  - url: https://api.example.com
    description: 外部向けAPIサーバ
paths:
  /public/data:
    get:
      summary: 公開データ取得
      responses:
        '200':
          description: 成功
        '404':
          $ref: 'components.yaml#/components/responses/NotFound'
  /api/v1/auth: 
    $ref: './api/v1/auth.yaml#/user_registration'
  /api/v1/auth/sign_in: 
    $ref: './api/v1/auth.yaml#/sign_in'
  /api/v1/auth/sign_out: 
    $ref: './api/v1/auth.yaml#/sign_out'
  /api/v1/books:
    get:
      $ref: './api/v1/books.yaml#/get_books'
    post:
      $ref: './api/v1/books.yaml#/create_book' 
  /api/v1/users/books: 
    get:
      $ref: './api/v1/users/book.yaml#/get_user_books'
    post:
      $ref: './api/v1/users/book.yaml#/register_user_book'
