openapi: 3.0.0
info:
  title: Backend Internal API
  version: 1.0.0
  description: 内部向けのAPI定義
servers:
  - url: https://internal-api.example.com
    description: 内部向けAPIサーバ
paths:
  /internal/stats:
    get:
      summary: システム統計情報取得
      responses:
        '200':
          description: 成功
        '404':
          $ref: 'components.yaml#/components/responses/NotFound'
