name: Docker Image CI for API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'rails-api/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    outputs:
      api_digest: ${{ steps.push-api.outputs.digest }}
      changed: ${{ steps.check_changes.outputs.api-changed }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    # - name: Check for changes in rails directory
    #   id: check_changes
    #   run: |
    #     if git diff --quiet stable^ stable -- rails; then
    #       echo "No changes detected in rails directory."
    #       echo "api-changed=false" >> $GITHUB_OUTPUT
    #     else
    #       echo "Changes detected in rails directory."
    #       echo "api-changed=true" >> $GITHUB_OUTPUT
    #     fi

    - name: Log in to Docker Hub for api
      # if: steps.check_changes.outputs.api-changed == 'true'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME_API }}
        password: ${{ secrets.DOCKER_PASSWORD_API }}

    - name: Extract metadata (tags, labels) for Docker
      # if: steps.check_changes.outputs.api-changed == 'true'
      id: meta-api
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ secrets.DOCKER_USERNAME_API }}/api

    - name: Build and push api-server Docker image
      # if: steps.check_changes.outputs.api-changed == 'true'
      id: push-api
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./rails-api
        file: ./rails-api/Dockerfile.api
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}

  update_manifest_repository:
    name: Update manifest repository
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    needs: push_to_registry
    # if: ${{ needs.push_to_registry.outputs.changed == 'true' }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.MANIFEST_REPO_OWNER }}/${{ secrets.MANIFESTS_REPO }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Update image in Kubernetes manifest using sed
      run: |
        sed -i 's|image: .*|image: ${{ secrets.DOCKER_USERNAME_API }}/api@${{ needs.push_to_registry.outputs.api_digest }}|' ./overlays/lab/api.yaml

    - name: Commit api digest changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./overlays/lab/api.yaml
        git commit -m "Update api digest in Kubernetes manifest"
        git push